### ISSUE TITLE
询问

### ISSUE THREAD

**Issue by Xingqi-Apple** [thuhole/database_backup#8]
，催更新

**Comment by erbanku** [comment]
@Xingqi-Apple 匿名化处理后怕什么呀，该是什么就是什么，他们舆论攻击咱我们还能攻击回去呢。

（感谢管理员同学们，幸苦了。）

> 1、担心是否会被校外人员获取，进一步处于不明、不法目的（博人眼球）对其中的个别言论发动舆论进行攻击 2、工作的同学辛苦了，大概啥时候好呀，催更新
